// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPx8VIA7kIY-L5Bwgkn9quOe1ygF8wyDI',
    appId: '1:388691551749:web:2c6a34334db8d4a8ad5e6c',
    messagingSenderId: '388691551749',
    projectId: 'mypokeapp-d2279',
    authDomain: 'mypokeapp-d2279.firebaseapp.com',
    storageBucket: 'mypokeapp-d2279.appspot.com',
    measurementId: 'G-QMERSSYC9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4BjQGHpm9uRl-ujNy0303wd6Dbh-4MiY',
    appId: '1:388691551749:android:8424890812ef78d8ad5e6c',
    messagingSenderId: '388691551749',
    projectId: 'mypokeapp-d2279',
    storageBucket: 'mypokeapp-d2279.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM6i1CZ7VXKM02IFFPdXmtrCyKQmpJ994',
    appId: '1:388691551749:ios:3c65a4b5cdaf8966ad5e6c',
    messagingSenderId: '388691551749',
    projectId: 'mypokeapp-d2279',
    storageBucket: 'mypokeapp-d2279.appspot.com',
    iosBundleId: 'com.example.myPokeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM6i1CZ7VXKM02IFFPdXmtrCyKQmpJ994',
    appId: '1:388691551749:ios:2a15abd5bc6ac70bad5e6c',
    messagingSenderId: '388691551749',
    projectId: 'mypokeapp-d2279',
    storageBucket: 'mypokeapp-d2279.appspot.com',
    iosBundleId: 'com.example.myPokeApp.RunnerTests',
  );
}
